### ISSUE TITLE
make `XmlSerializer`'s properties accessable

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-php-library#305]
`XmlSerializer`'s properties `xmlVersion` and `xmlEncoding` are currently private.
goal: make them visible/accessible for inheriting structures.
caused by https://github.com/CycloneDX/cyclonedx-php-library/discussions/304#discussioncomment-6056157

----

options for a solution: 
* a) add protected getters
* b) make properties protected readonly -- since this lib requires `php:^8.1`

preferred solution: b)

----

this is considered a non-breaking change, as an access is widened.

**Comment by jkowalleck** [comment]
@llaville FYI

**Comment by llaville** [comment]
preferred solution b) too !
